name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - azure-deployment
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - azure-deployment

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_BUSH_068ED6F03 }}
          action: "upload"
          ###### Konfigurasi Build ######
          app_location: "veda_frontend"       # Jalur relatif tanpa garis miring di depan
          api_location: ""                   # Kosongkan
          output_location: "dist"             # Folder hasil build Vite
          ###### Akhir Konfigurasi ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
